# Generated by Django 4.0.3 on 2022-03-26 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTrader', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TradingStrategies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idStrategy', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('activo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=140)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInvest.traders')),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTrade', models.IntegerField()),
                ('activo', models.CharField(max_length=40)),
                ('tradeDirection', models.IntegerField(choices=[(0, 'Buy'), (1, 'Sell')])),
                ('typeentry', models.IntegerField(choices=[(0, 'Entry'), (1, 'Exit')], default=0)),
                ('precio', models.FloatField()),
                ('descripcion', models.CharField(max_length=140)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppInvest.tradingstrategies')),
            ],
        ),
    ]
