# Generated by Django 4.0.3 on 2022-04-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInvest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trades',
            name='idTrade',
        ),
        migrations.RemoveField(
            model_name='tradingstrategies',
            name='idStrategy',
        ),
    ]
