# Generated by Django 4.0.3 on 2022-04-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInvest', '0004_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='imagen',
            new_name='avatar',
        ),
    ]
