# Generated by Django 4.0.3 on 2022-04-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInvest', '0005_rename_imagen_avatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, default='user_default_profile.png', null=True, upload_to='avatar'),
        ),
    ]
