# Generated by Django 4.0.3 on 2022-04-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInvest', '0006_alter_avatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
