# Generated by Django 4.0.3 on 2022-04-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInvest', '0008_alter_avatar_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trades',
            old_name='activo',
            new_name='asset',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='precio',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='trades',
            name='comission',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trades',
            name='comment',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='trades',
            name='fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trades',
            name='stopPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trades',
            name='swap',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trades',
            name='time',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trades',
            name='tpPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trades',
            name='volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
