# Generated by Django 4.0.3 on 2022-04-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInvest', '0010_trades_balance_trades_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='tradeDirection',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trades',
            name='typeentry',
            field=models.IntegerField(),
        ),
    ]
